module.exports = {
  // ...existing code...
  images: {
    // ...existing code...
    domains: [
      // ...existing domains...
      "example.com"
    ],
    // ...existing code...
  },
  // ...existing code...
};